from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean
from database import Base
import datetime

class Article(Base):
    __tablename__ = "articles"

    id = Column(Integer, primary_key=True, index=True)
    external_id = Column(String, unique=True, index=True) # The ID from RSS
    title = Column(String, index=True)
    source = Column(String)
    url = Column(String, index=True)
    summary = Column(Text) # Original summary/description
    ai_summary = Column(Text, nullable=True) # Generated by AI
    image_url = Column(String, nullable=True) # Lead image URL
    category = Column(String, default="General")
    published_at = Column(DateTime, default=datetime.datetime.utcnow)
    is_bookmarked = Column(Boolean, default=False)
